
LIBFOUNDATION_SRC += $(LIBFOUNDATION_DIR)/tiny_alloc.c
LIBFOUNDATION_SRC += $(LIBFOUNDATION_DIR)/tiny_printf.c
LIBFOUNDATION_SRC += $(LIBFOUNDATION_DIR)/utils.c
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/system_alloc.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/virtual_eeprom.cpp

LIBFOUNDATION_INC += -I$(LIBFOUNDATION_DIR)/include


