
CRT0_OBJECT += $(LIBSTM32_DIR)/src/crt0.o
LIBSTM32_SRC += $(LIBSTM32_DIR)/src/system.c
LIBSTM32_SRC += $(LIBSTM32_DIR)/src/usart_simple.c
LIBSTM32_CPPSRC += $(LIBSTM32_DIR)/src/stm32fmc.cpp
LIBSTM32_INC += -I$(LIBSTM32_DIR)/inc -DCPP_STARTUP_CODE

LIBSTM32_LIB = $(LIBSTM32_DIR)/libstm32lite.a
LIBSTM32_OBJS += $(LIBSTM32_SRC:%.c=%.o) $(LIBSTM32_CPPSRC:%.cpp=%.o)
DEPFILES += $(LIBSTM32_SRC:%.c=%.dep) $(LIBSTM32_CPPSRC:%.cpp=%.dep)

$(LIBSTM32_LIB): $(LIBSTM32_OBJS)
	$(AR) $(ARFLAGS) $@ $^

LIBS += $(LIBSTM32_LIB)
LIBS_OBJS += $(LIBSTM32_OBJS) $(CRT0_OBJECT)

