#Base folder LIBENERGYMETER_DIR dir
LIBENERGYMETERSRC_DIR = $(LIBENERGYMETER_DIR)/src
LIBENERGYMETERINC_DIR = $(LIBENERGYMETER_DIR)/include

LIBENERGYMETER_INC = -I$(LIBENERGYMETERINC_DIR)
LIBENERGYMETER_CPPSRC =  $(wildcard $(LIBENERGYMETERSRC_DIR)/*.cpp)


LIBENERGYMETER_OBJS = $(LIBENERGYMETER_CPPSRC:%.cpp=%.o)
LIBENERGYMETER_LIB =  $(LIBENERGYMETER_DIR)/libenergymeter.a
DEPFILES +=   $(LIBENERGYMETER_CPPSRC:%.cpp=%.dep)

.ONESHELL:
$(LIBENERGYMETER_LIB): $(LIBENERGYMETER_OBJS)
	    $(AR) $(ARFLAGS) $@ $^

LIBS += $(LIBENERGYMETER_LIB)
LIBS_OBJS += $(LIBENERGYMETER_OBJS)
COMMON_FLAGS += $(LIBENERGYMETER_INC)
