#!/usr/bin/env python

_mbedtls_version = '2.1.1'
_mbedtls_dir = 'mbedtls-%s' % _mbedtls_version

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    src = bld.path.ant_glob( '%s/library/*.c'%_mbedtls_dir )
    inc = ['%s/include' % _mbedtls_dir ]
    bld.stlib( source=src,
            includes = inc, export_includes=inc,
            target='mbedtls', use= ['foundation', 'tcpip' ]
    )
