#!/usr/bin/env python

import platform



def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    src = bld.path.ant_glob( 'kernel/*.c' )
    src += bld.path.ant_glob( 'arch/arm-cm3/*.c' )
    inc = ['./include', './arch/arm-cm3/include' , '../libstm32/inc' ]
    bld( includes = inc, export_includes= inc, name = 'com_inc' )
    bld.stlib( source=src, target='isix', use = 'com_inc',
            cflags= ['-std=gnu11', '-mthumb' , '-mcpu=cortex-m3' ]
            )


