;/**
 * =====================================================================================
 * 	File: dsi_regs.hpp
 * 	Created Date: Sunday, August 18th 2019, 5:00:10 pm
 * 	Author: Lucjan Bryndza
 * 	Copyright (c) 2019 BoFF
 * 
 * 	GPL v2/3
 * =====================================================================================
 */
#pragma once
namespace periph::display::bus::detail {
static constexpr auto	DSI_VR		        =0x0000 ;/* DSI Host Version Register */
static constexpr auto	DSI_CR		        =0x0004 ;/* DSI Host Control Register */
static constexpr auto	 CR_EN		        =(1 << 0) ;/* DSI Host is enabled */
static constexpr auto	DSI_CCR		        =0x0008 ;/* DSI Host Clock Control Register */
static constexpr auto	 CCR_TOCKDIV_S	    =8 ;/* Timeout Clock Division */
static constexpr auto	 CCR_TOCKDIV_M	    =0xff;
static constexpr auto	 CCR_TXECKDIV_S	    =0 ;/* TX Escape Clock Division */
static constexpr auto	 CCR_TXECKDIV_M	    =0xff;
static constexpr auto	DSI_LVCIDR	        =0x000C ;/* DSI Host LTDC VCID Register */
static constexpr auto	 LVCIDR_VCID_S	    =0 ;/* Virtual Channel ID */
static constexpr auto	 LVCIDR_VCID_M	    =0x3;
static constexpr auto	DSI_LCOLCR	        =0x0010 ;/* DSI Host LTDC Color Coding Register */
static constexpr auto	 LCOLCR_LPE	        =(1 << 8) ;/* Loosely Packet Enable */
static constexpr auto	 LCOLCR_COLC_S	    =0 ;/* Color Coding */
static constexpr auto	 LCOLCR_COLC_M	    =0xf;
static constexpr auto	 LCOLCR_COLC_16_1	=0x0 ;/* 16-bit */
static constexpr auto	 LCOLCR_COLC_16_2	=0x1 ;/* 16-bit */
static constexpr auto	 LCOLCR_COLC_16_3	=0x2 ;/* 16-bit */
static constexpr auto	 LCOLCR_COLC_18_1	=0x3 ;/* 18-bit */
static constexpr auto	 LCOLCR_COLC_18_2	=0x4 ;/* 18-bit */
static constexpr auto	 LCOLCR_COLC_24		=0x5 ;/* 24-bit */
static constexpr auto	DSI_LPCR	        =0x0014 ;/* DSI Host LTDC Polarity Configuration Register */
static constexpr auto	 LPCR_HSP	        =(1 << 2) ;/* HSYNC Polarity */
static constexpr auto	 LPCR_VSP	        =(1 << 1) ;/* VSYNC Polarity */
static constexpr auto	 LPCR_DEP	        =(1 << 0) ;/* Data Enable Polarity */
static constexpr auto	DSI_LPMCR	        =0x0018 ;/* DSI Host Low-Power mode Configuration Register */
static constexpr auto	 LPMCR_LPSIZE_S		=16 ;/* Largest Packet Size */
static constexpr auto	 LPMCR_LPSIZE_M		=0xff;
static constexpr auto	 LPMCR_VLPSIZE_S	=0 ;/* VACT Largest Packet Size */
static constexpr auto	 LPMCR_VLPSIZE_M	=0xff;
static constexpr auto	DSI_PCR		        =0x002C ;/* DSI Host Protocol Configuration Register */
static constexpr auto	DSI_GVCIDR	        =0x0030 ;/* DSI Host Generic VCID Register */
static constexpr auto	DSI_MCR		        =0x0034 ;/* DSI Host mode Configuration Register */
static constexpr auto	 MCR_CMDM	        =(1 << 0) ;/* Command mode. Reset value */
static constexpr auto	DSI_VMCR	        =0x0038 ;/* DSI Host Video mode Configuration Register */
static constexpr auto	 VMCR_LPCE	        =(1 << 15) ;/* Low-Power Command Enable */
static constexpr auto	 VMCR_FBTAAE	    =(1 << 14) ;/* Frame Bus-Turn-Around Acknowledge Enable */
static constexpr auto	 VMCR_LPHFPE	    =(1 << 13) ;/* Low-Power Horizontal Front-Porch Enable */
static constexpr auto	 VMCR_LPHBPE	    =(1 << 12) ;/* Low-Power Horizontal Back-Porch Enable */
static constexpr auto	 VMCR_LPVAE	        =(1 << 11) ;/* Low-Power Vertical Active Enable */
static constexpr auto	 VMCR_LPVFPE	    =(1 << 10) ;/* Low-power Vertical Front-porch Enable */
static constexpr auto	 VMCR_LPVBPE	    =(1 << 9) ;/* Low-power Vertical Back-Porch Enable */
static constexpr auto	 VMCR_LPVSAE	    =(1 << 8) ;/* Low-Power Vertical Sync Active Enable */
static constexpr auto	 VMCR_VMT_S	        =0 ;/* Video mode Type */
static constexpr auto	 VMCR_VMT_M	        =0x3;
static constexpr auto	 VMCR_VMT_PULS	    =0;
static constexpr auto	 VMCR_VMT_EVNT	    =1;
static constexpr auto	 VMCR_VMT_BRST	    =2;
static constexpr auto	DSI_VPCR	        =0x003C ;/* DSI Host Video Packet Configuration Register */
static constexpr auto	 VPCR_VPSIZE_S	    =0 ;/* Video Packet Size */
static constexpr auto	 VPCR_VPSISE_M	    =0x3fff;
static constexpr auto	DSI_VCCR	        =0x0040 ;/* DSI Host Video Chunks Configuration Register */
static constexpr auto	 VCCR_NUMC_S	    =0 ;/* Number of Chunks */
static constexpr auto	 VCCR_NUMC_M	    =0x1fff;
static constexpr auto	DSI_VNPCR	        =0x0044 ;/* DSI Host Video Null Packet Configuration Register */
static constexpr auto	 VNPCR_NPSIZE_S	    =0 ;/* Null Packet Size */
static constexpr auto	 VNPCR_NPSIZE_M	    =0x1fff;
static constexpr auto	DSI_VHSACR	        =0x0048 ;/* DSI Host Video HSA Configuration Register */
static constexpr auto	DSI_VHBPCR	        =0x004C ;/* DSI Host Video HBP Configuration Register */
static constexpr auto	DSI_VLCR	        =0x0050 ;/* DSI Host Video Line Configuration Register */
static constexpr auto	DSI_VVSACR	        =0x0054 ;/* DSI Host Video VSA Configuration Register */
static constexpr auto	DSI_VVBPCR	        =0x0058 ;/* DSI Host Video VBP Configuration Register */
static constexpr auto	DSI_VVFPCR	        =0x005C ;/* DSI Host Video VFP Configuration Register */
static constexpr auto	DSI_VVACR	        =0x0060 ;/* DSI Host Video VA Configuration Register */
static constexpr auto	DSI_LCCR	        =0x0064 ;/* DSI Host LTDC Command Configuration Register */
static constexpr auto	DSI_CMCR	        =0x0068 ;/* DSI Host Command mode Configuration Register */
static constexpr auto	DSI_GHCR	        =0x006C ;/* DSI Host Generic Header Configuration Register */
static constexpr auto	 GHCR_WCMSB_S	    =16 ;/* WordCount MSB */
static constexpr auto	 GHCR_WCMSB_M	    =0xff;
static constexpr auto	 GHCR_WCLSB_S	    =8 ;/* WordCount LSB */
static constexpr auto	 GHCR_WCLSB_M	    =0xff;
static constexpr auto	 GHCR_VCID_S	    =6 ;/* Channel */
static constexpr auto	 GHCR_VCID_M	    =0x3;
static constexpr auto	 GHCR_DT_S	        =0 ;/* Type */
static constexpr auto	 GHCR_DT_M	        =0x3f;
static constexpr auto	DSI_GPDR	        =0x0070 ;/* DSI Host Generic Payload Data Register */
static constexpr auto	DSI_GPSR	        =0x0074 ;/* DSI Host Generic Packet Status Register */
static constexpr auto	 GPSR_CMDFF	        =(1 << 1) ;/* Command FIFO Full */
static constexpr auto	 GPSR_CMDFE	        =(1 << 0) ;/* Command FIFO Empty */
static constexpr auto	DSI_TCCR0	        =0x0078 ;/* DSI Host Timeout Counter Configuration Register 0 */
static constexpr auto	DSI_TCCR1	        =0x007C ;/* DSI Host Timeout Counter Configuration Register 1 */
static constexpr auto	DSI_TCCR2	        =0x0080 ;/* DSI Host Timeout Counter Configuration Register 2 */
static constexpr auto	DSI_TCCR3	        =0x0084 ;/* DSI Host Timeout Counter Configuration Register 3 */
static constexpr auto	DSI_TCCR4	        =0x0088 ;/* DSI Host Timeout Counter Configuration Register 4 */
static constexpr auto	DSI_TCCR5	        =0x008C ;/* DSI Host Timeout Counter Configuration Register 5 */
static constexpr auto	DSI_CLCR	        =0x0094 ;/* DSI Host Clock Lane Configuration Register */
static constexpr auto	 CLCR_ACR	        =(1 << 1) ;/* Automatic Clock lane Control */
static constexpr auto	 CLCR_DPCC          =(1 << 0) ;/* D-PHY Clock Control */
static constexpr auto	DSI_CLTCR	        =0x0098 ;/* DSI Host Clock Lane Timer Configuration Register */
static constexpr auto	DSI_DLTCR	        =0x009C ;/* DSI Host Data Lane Timer Configuration Register */
static constexpr auto	DSI_PCTLR	        =0x00A0 ;/* DSI Host PHY Control Register */
static constexpr auto	 PCTLR_CKE	        =(1 << 2) ;/* Clock Enable */
static constexpr auto	 PCTLR_DEN	        =(1 << 1) ;/* Digital Enable */
static constexpr auto	DSI_PCONFR      	=0x00A4 ;/* DSI Host PHY Configuration Register */
static constexpr auto	 SW_TIME_S      	=8 ;/* Stop Wait Time */
static constexpr auto	 SW_TIME_M	        =0xff;
static constexpr auto	 PCONFR_NL_S	    =0 ;/* Number of Lanes */
static constexpr auto	 PCONFR_NL_M	    =0x3;
static constexpr auto	 PCONFR_NL_1	    =(0 << PCONFR_NL_S);
static constexpr auto	 PCONFR_NL_2	    =(1 << PCONFR_NL_S)	;/* Reset value */
static constexpr auto	DSI_PUCR	    = 0x00A8 ;/* DSI Host PHY ULPS Control Register */
static constexpr auto	DSI_PTTCR	    = 0x00AC ;/* DSI Host PHY TX Triggers Configuration Register */
static constexpr auto	DSI_PSR		    = 0x00B0 ;/* DSI Host PHY Status Register */
static constexpr auto	DSI_ISR0	    = 0x00BC ;/* DSI Host Interrupt & Status Register 0 */
static constexpr auto	DSI_ISR1	    = 0x00C0 ;/* DSI Host Interrupt & Status Register 1 */
static constexpr auto	DSI_IER0	    = 0x00C4 ;/* DSI Host Interrupt Enable Register 0 */
static constexpr auto	DSI_IER1	    = 0x00C8 ;/* DSI Host Interrupt Enable Register 1 */
static constexpr auto	DSI_FIR0	    = 0x00D8 ;/* DSI Host Force Interrupt Register 0 */
static constexpr auto	DSI_FIR1	    = 0x00DC ;/* DSI Host Force Interrupt Register 1 */
static constexpr auto	DSI_VSCR	    = 0x0100 ;/* DSI Host Video Shadow Control Register */
static constexpr auto	DSI_LCVCIDR	    = 0x010C ;/* DSI Host LTDC Current VCID Register */
static constexpr auto	DSI_LCCCR	    = 0x0110 ;/* DSI Host LTDC Current Color Coding Register */
static constexpr auto	DSI_LPMCCR  	= 0x0118 ;/* DSI Host Low-Power mode Current Configuration */
static constexpr auto	DSI_VMCCR	    = 0x0138 ;/* DSI Host Video mode Current Configuration Register */
static constexpr auto	DSI_VPCCR	    = 0x013C ;/* DSI Host Video Packet Current Configuration Register */
static constexpr auto	DSI_VCCCR	    = 0x0140 ;/* DSI Host Video Chunks Current Configuration Register */
static constexpr auto	DSI_VNPCCR	    = 0x0144 ;/* DSI Host Video Null Packet Current Configuration Register */
static constexpr auto	DSI_VHSACCR	    = 0x0148 ;/* DSI Host Video HSA Current Configuration Register */
static constexpr auto	DSI_VHBPCCR	    = 0x014C ;/* DSI Host Video HBP Current Configuration Register */
static constexpr auto	DSI_VLCCR	    = 0x0150 ;/* DSI Host Video Line Current Configuration Register (DSI_VLCCR) */
static constexpr auto	DSI_VVSACCR	    = 0x0154 ;/* DSI Host Video VSA Current Configuration Register */
static constexpr auto	DSI_VVBPCCR	    = 0x0158 ;/* DSI Host Video VBP Current Configuration Register */
static constexpr auto	DSI_VVFPCCR	    = 0x015C ;/* DSI Host Video VFP Current Configuration Register */
static constexpr auto	DSI_VVACCR  	= 0x0160 ;/* DSI Host Video VA Current Configuration Register */
static constexpr auto	DSI_WCFGR	    = 0x0400 ;/* DSI Wrapper Configuration Register */
static constexpr auto	 WCFGR_VSPOL	= (1 << 7) ;/* VSync Polarity */
static constexpr auto	 WCFGR_AR	    = (1 << 6) ;/* Automatic Refresh */
static constexpr auto	 WCFGR_TEPOL	= (1 << 5) ;/* TE Polarity */
static constexpr auto	 WCFGR_TESRC	= (1 << 4) ;/* TE Source */
static constexpr auto	 WCFGR_COLMUX_S	= 1 ;/* Color Multiplexing */
static constexpr auto	 WCFGR_COLMUX_M	= 0x7;
static constexpr auto	 COLMUX_16_1	= 0x0 ;/* 16-bit */
static constexpr auto	 COLMUX_16_2	= 0x1 ;/* 16-bit */
static constexpr auto	 COLMUX_16_3	= 0x2 ;/* 16-bit */
static constexpr auto	 COLMUX_18_1	= 0x3 ;/* 18-bit */
static constexpr auto	 COLMUX_18_2	= 0x4 ;/* 18-bit */
static constexpr auto	 COLMUX_24	    = 0x5 ;/* 24-bit */
static constexpr auto	 WCFGR_DSIM	    = (1 << 0) ;/* DSI mode */
static constexpr auto	DSI_WCR		    = 0x0404 ;/* DSI Wrapper Control Register */
static constexpr auto	 WCR_DSIEN	    = (1 << 3) ;/* DSI Enable */
static constexpr auto	 WCR_LTDCEN 	= (1 << 2) ;/* LTDC Enable */
static constexpr auto	 WCR_SHTDN	    = (1 << 1) ;/* Shutdown */
static constexpr auto	 WCR_COLM	    = (1 << 0) ;/* Color mode */
static constexpr auto	DSI_WIER	    = 0x0408 ;/* DSI Wrapper Interrupt Enable Register */
static constexpr auto	DSI_WISR	    = 0x040C ;/* DSI Wrapper Interrupt & Status Register */
static constexpr auto	 WISR_RRIF	    = (1 << 13) ;/* Regulator Ready Interrupt Flag */
static constexpr auto	 WISR_RRS	    = (1 << 12) ;/* Regulator Ready Status */
static constexpr auto	 WISR_PLLUIF	= (1 << 10) ;/* PLL Unlock Interrupt Flag */
static constexpr auto	 WISR_PLLLIF	= (1 << 9) ;/* PLL Lock Interrupt Flag */
static constexpr auto	 WISR_PLLLS	    = (1 << 8) ;/* PLL Lock Status */
static constexpr auto	 WISR_BUSY  	= (1 << 2) ;/* Busy Flag */
static constexpr auto	 WISR_ERIF	    = (1 << 1) ;/* End of Refresh Interrupt Flag */
static constexpr auto	 WISR_TEIF	    = (1 << 0) ;/* Tearing Effect Interrupt Flag */
static constexpr auto	DSI_WIFCR	    = 0x0410 ;/* DSI Wrapper Interrupt Flag Clear Register */
static constexpr auto	DSI_WPCR0	    = 0x0418 ;/* DSI Wrapper PHY Configuration Register 0 */
static constexpr auto	 WPCR0_UIX4_S	= 0 ;/* Unit Interval multiplied by 4 */
static constexpr auto	 WPCR0_UIX4_M	= 0x3f;
static constexpr auto	DSI_WPCR1	    = 0x041C ;/* DSI Wrapper PHY Configuration Register 1 */
static constexpr auto	DSI_WPCR2	    = 0x0420 ;/* DSI Wrapper PHY Configuration Register 2 */
static constexpr auto	DSI_WPCR3	    = 0x0424 ;/* DSI Wrapper PHY Configuration Register 3 */
static constexpr auto	DSI_WPCR4	    = 0x0428 ;/* DSI Wrapper PHY Configuration Register 4 */
static constexpr auto	DSI_WRPCR	    = 0x0430 ;/* DSI Wrapper Regulator and PLL Control Register */
static constexpr auto	 WRPCR_REGEN	= (1 << 24)	;/* Regulator Enable */
static constexpr auto	 WRPCR_ODF_S	= 16;		;/* PLL Output Division Factor */
static constexpr auto	 WRPCR_ODF_M	= 0x3;
static constexpr auto	 WRPCR_IDF_S	= 11		;/* PLL Input Division Factor */
static constexpr auto	 WRPCR_IDF_M	= 0xf;
static constexpr auto	 WRPCR_NDIV_S	= 2		;/* PLL Loop Division Factor */
static constexpr auto	 WRPCR_NDIV_M	= 0x7f;
static constexpr auto	 WRPCR_PLLEN	= (1 << 0)	;/* PLL Enable */

}
