#Base folder LIBGFX_DIR dir
LIBGFXSRC_DIR = $(LIBGFX_DIR)/src
LIBGFXINC_DIR = $(LIBGFX_DIR)/include
LIBGFX_DRVDISP_SRC_DIR = $(LIBGFX_DIR)/drivers/disp

LIBGFX_INC = -I$(LIBGFXINC_DIR)

LIBGFX_DRV_CPPSRC = $(LIBGFX_DRVDISP_SRC_DIR)/ili9341.cpp


LIBGFX_OBJS = $(LIBGFX_CPPSRC:%.cpp=%.o) $(LIBGFX_DRV_CPPSRC:%.cpp=%.o) 
LIBGFX_LIB =  $(LIBGFX_DIR)/libgfx.a
DEPFILES +=   $(LIBGFX_CPPSRC:%.cpp=%.dep) $(LIBGFX_DRV_CPPSRC:%.cpp=%.dep)

.ONESHELL:
$(LIBGFX_LIB): $(LIBGFX_OBJS)
	    $(AR) $(ARFLAGS) $@ $^

LIBS += $(LIBGFX_LIB)
LIBS_OBJS += $(LIBGFX_OBJS)
COMMON_FLAGS += $(LIBGFX_INC)
