#!/usr/bin/env python

def options(opt):
    pass

def configure(cfg):
    cfg.define( 'CONFIG_ISIX_USE_TIMERS' , 1 )

def build(bld):
    src = bld.path.ant_glob( '**/*.c', excl='host-tools' )
    src += bld.path.ant_glob( '**/*.cpp', excl='host-tools' )
    inc = ['include' ]
    bld.stlib( source=src,
            includes = inc, export_includes=inc,
            target='graphics', use=['isix', 'foundation', 'periph' ]
    )
