#Base folder LIBFSFAT_DIR dir
LIFSFATSRC_DIR = $(LIBFSFAT_DIR)/src
LIFSFATINC_DIR = $(LIBFSFAT_DIR)/include
LIBFSFATOSRC_DIR = $(LIFSFATSRC_DIR)/option

LIBFSFAT_SRC  = $(LIFSFATSRC_DIR)/ff.c 
LIBFSFAT_CPPSRC = $(LIFSFATSRC_DIR)/diskio.cpp
LIBFSFAT_SRC += $(LIBFSFATOSRC_DIR)/unicode.c  $(LIBFSFATOSRC_DIR)/syscall.c
LIBFSFAT_INC = -I$(LIFSFATINC_DIR)

LIBFSFAT_OBJS = $(LIBFSFAT_SRC:%.c=%.o) $(LIBFSFAT_CPPSRC:%.cpp=%.o) 
LIBFSFAT_LIB =  $(LIBFSFAT_DIR)/libfsfat.a
DEPFILES +=     $(LIBFSFAT_SRC:%.c=%.dep) $(LIBFSFAT_CPPSRC:%.cpp=%.dep) 

.ONESHELL:
$(LIBFSFAT_LIB): $(LIBFSFAT_OBJS)
	    $(AR) $(ARFLAGS) $@ $^

LIBS += $(LIBFSFAT_LIB)
LIBS_OBJS += $(LIBFSFAT_OBJS)
COMMON_FLAGS += $(LIBFSFAT_INC)
