#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    src = bld.path.ant_glob( 'src/*.c' )
    src += bld.path.ant_glob( 'src/*.cpp' )
    src += [ 'src/option/unicode.c', 'src/option/syscall.c' ]
    inc = ['include' ]
    bld.stlib( source=src,
            includes = inc, export_includes=inc,
            target='fatfs',
            use=['isix', 'isixdrvstm32', 'common_conf' ]
    )
