#!/usr/bin/env python

_lwip_ver = "1.4.1"

def options(opt):
    pass

def configure(conf):
    conf.define('CONFIG_ISIX_USE_TIMERS',1)
    #conf.define('ISIX_TCPIPLIB_CHECKSUM_BY_HARDWARE',1)
    #conf.define('ISIX_TCPIPLIB_ETHERNET',1)

def build(bld):
    _lwip = 'lwip-%s/src' % _lwip_ver
    _src = bld.path.ant_glob( _lwip + '/core/*.c' )
    _src += bld.path.ant_glob( _lwip + '/core/ipv4/*.c' )
    _src += bld.path.ant_glob( _lwip + '/core/snmp/*.c' )
    _src += bld.path.ant_glob( _lwip + '/api/*.c' )
    _src += bld.path.ant_glob( _lwip + '/netif/*.c' )
    _src += bld.path.ant_glob( _lwip + '/netif/ppp/*.c' )
    _src += bld.path.ant_glob( 'port/*.c' )
    _src += bld.path.ant_glob( 'port/*.cpp' )
    _inc = [ 'include', _lwip+'/include', _lwip+'/include/ipv4', 'port/include']
    bld.stlib( source=_src, target='tcpip', cflags=['-Wno-implicit-fallthrough'],
               includes=_inc, export_includes=_inc,
               use = [ 'foundation' ]
    )

