ifneq ($(ISIX_ARCH),simunix-x86)
LIBFOUNDATION_O_CPPSRC += $(LIBFOUNDATION_DIR)/syscalls.cpp
endif
LIBFOUNDATION_SRC += $(LIBFOUNDATION_DIR)/tiny_alloc.c
LIBFOUNDATION_SRC += $(LIBFOUNDATION_DIR)/tiny_printf.c
LIBFOUNDATION_SRC += $(LIBFOUNDATION_DIR)/utils.c
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/util_dtoa.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/util_ftoa.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/virtual_eeprom.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/hd44xx_display.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/uc1601_display.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/i2c_eeprom.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/fs_env.cpp
LIBFOUNDATION_CPPSRC += $(LIBFOUNDATION_DIR)/md5sum.cpp
LIBFOUNDATION_INC += -I$(LIBFOUNDATION_DIR)/include
LIBFOUNDATION_LIB = $(LIBFOUNDATION_DIR)/libfoundation.a
LIBFOUNDATION_OBJS += $(LIBFOUNDATION_SRC:%.c=%.o) $(LIBFOUNDATION_CPPSRC:%.cpp=%.o)
DEPFILES += $(LIBFOUNDATION_SRC:%.c=%.dep) $(LIBFOUNDATION_CPPSRC:%.cpp=%.dep) $(LIBFOUNDATION_O_CPPSRC:%.cpp=%.dep)

.ONESHELL:
$(LIBFOUNDATION_LIB): $(LIBFOUNDATION_OBJS)
	    $(AR) $(ARFLAGS) $@ $^

LIBS += $(LIBFOUNDATION_LIB)
CRT0_OBJECTS += $(LIBFOUNDATION_O_CPPSRC:%.cpp=%.o)
LIBS_OBJS += $(LIBFOUNDATION_OBJS) $(CRT0_OBJECTS)
COMMON_FLAGS += $(LIBFOUNDATION_INC)
