#!/usr/bin/env python


def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    src = bld.path.ant_glob( '*.c' )
    src += bld.path.ant_glob( '*.cpp' )
    inc = ['./include' ]
    bld.stlib( source=src,
            includes = inc, export_includes=inc,
            target='foundation', use= ['isix', 'common_conf']
    )
    #bld.objects( source='syscalls.cpp', includes = inc,
    #        target='crt0', name= 'syscalls', use=['isix']
    #)



