#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    src = bld.path.ant_glob( 'src/*.cpp' )
    inc = ['include' ]
    bld.stlib( source=src,
            includes = inc, export_includes=inc,
            target='gsm', use= ['foundation']
    )
